apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-provisioning
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "config/provisioning/dashboards/*").AsConfig | nindent 2 }}
  {{- (.Files.Glob "config/provisioning/alerting/*").AsConfig | nindent 2 }}
