apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "config/provisioning/datasources/*").AsConfig | nindent 2 }}
