server:
  port: ${SERVER_PORT:8080}
spring:
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 3000
            response-timeout: 10s
      routes:
        - id: accountsRoute
          uri: lb://accounts-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1
            - name: JwtTokenRelay
        - id: cashRoute
          uri: lb://cash-service
          predicates:
            - Path=/api/cash/**
          filters:
            - StripPrefix=1
            - name: JwtTokenRelay
        - id: transferRoute
          uri: lb://transfer-service
          predicates:
            - Path=/api/transfer/**
          filters:
            - StripPrefix=1
            - name: JwtTokenRelay
        - id: notificationsRoute
          uri: lb://notifications-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
            - name: JwtTokenRelay
