server:
  port: ${SERVER_PORT:8084}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/bank
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: notifications
    default-schema: notifications
    create-schemas: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: notifications
