apiVersion: 1

groups:
  - orgId: 1
    name: bank-app-alerts
    folder: Bank App
    interval: 1m
    rules:
      - uid: bank-http-5xx
        title: HTTP 5xx errors detected
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: code
              expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m]))
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              refId: B
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: HTTP 5xx error rate is above zero for the last 5 minutes.
          summary: HTTP 5xx errors detected
        labels:
          severity: warning
      - uid: bank-transfer-failed
        title: Transfer failures detected
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: code
              expr: sum(increase(bank_transfer_failed_total[5m]))
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              refId: B
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: At least one transfer failure occurred in the last 5 minutes.
          summary: Transfer failures detected
        labels:
          severity: warning
