apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts-service.fullname" . }}-secret
  labels:
    {{- include "accounts-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-user: {{ .Values.db.user | quote }}
  db-password: {{ .Values.db.password | quote }}
  client-secret: {{ .Values.oauth.clientSecret | quote }}
