apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash-service.fullname" . }}-secret
  labels:
    {{- include "cash-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.oauth.clientSecret | quote }}
