spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 3000
            response-timeout: 10s
      routes:
        - id: accountsRoute
          uri: http://accounts-service:8081
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1
            - name: JwtTokenRelay
        - id: cashRoute
          uri: http://cash-service:8082
          predicates:
            - Path=/api/cash/**
          filters:
            - StripPrefix=1
            - name: JwtTokenRelay
        - id: transferRoute
          uri: http://transfer-service:8083
          predicates:
            - Path=/api/transfer/**
          filters:
            - StripPrefix=1
            - name: JwtTokenRelay
        - id: notificationsRoute
          uri: http://notifications-service:8084
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
            - name: JwtTokenRelay
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_ISSUER_HOST:localhost}:${KEYCLOAK_ISSUER_PORT:8180}/realms/bank-realm
          jwk-set-uri: http://${KEYCLOAK_INTERNAL_HOST:localhost}:${KEYCLOAK_INTERNAL_PORT:8180}/realms/bank-realm/protocol/openid-connect/certs
server:
  port: ${SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
