fullnameOverride: notifications-service

replicaCount: 1

image:
  repository: local/notifications-service
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8084

db:
  host: postgres
  name: bank
  user: postgres
  password: postgres

kafka:
  bootstrapServers: kafka:9092
