spring:
  application:
    name: transfer-service
  security:
    oauth2:
      client:
        registration:
          transfer-client:
            client-id: transfer-service
            client-secret: transfer-secret
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          transfer-client:
            token-uri: http://${KEYCLOAK_INTERNAL_HOST:localhost}:${KEYCLOAK_INTERNAL_PORT:8180}/realms/bank-realm/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_ISSUER_HOST:localhost}:${KEYCLOAK_ISSUER_PORT:8180}/realms/bank-realm
          jwk-set-uri: http://${KEYCLOAK_INTERNAL_HOST:localhost}:${KEYCLOAK_INTERNAL_PORT:8180}/realms/bank-realm/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
server:
  port: ${SERVER_PORT:8083}
accounts:
  service:
    url: http://accounts-service:8081
    connect-timeout: 3s
    timeout: 5s
resilience4j:
  circuitbreaker:
    instances:
      accountsService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
  endpoint:
    health:
      show-details: always
logstash:
  host: ${LOGSTASH_HOST:logstash}
  port: ${LOGSTASH_PORT:5000}
