apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifications-service.fullname" . }}-config
  labels:
    {{- include "notifications-service.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.db.host | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
