apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifications-service.fullname" . }}-secret
  labels:
    {{- include "notifications-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-user: {{ .Values.db.user | quote }}
  db-password: {{ .Values.db.password | quote }}
