global:
  namespace: bank
  imageRegistry: local
  keycloak:
    internalHost: host.docker.internal
    internalPort: "8180"
    issuerHost: localhost
    issuerPort: "8180"

postgres:
  enabled: true

kafka:
  enabled: true

notifications-service:
  enabled: true
  image:
    repository: local/notifications-service
    pullPolicy: Never

accounts-service:
  enabled: true
  image:
    repository: local/accounts-service
    pullPolicy: Never

cash-service:
  enabled: true
  image:
    repository: local/cash-service
    pullPolicy: Never

transfer-service:
  enabled: true
  image:
    repository: local/transfer-service
    pullPolicy: Never

gateway-service:
  enabled: true
  image:
    repository: local/gateway-service
    pullPolicy: Never
  service:
    type: NodePort
    port: 8080
    nodePort: 30080

zipkin:
  enabled: true
  service:
    type: NodePort
    port: 9411
    nodePort: 30411

prometheus:
  enabled: true
  service:
    type: NodePort
    port: 9090
    nodePort: 30090

grafana:
  enabled: true
  service:
    type: NodePort
    port: 3000
    nodePort: 30300

elk:
  enabled: true
  logstash:
    service:
      nodePort: 30500
  kibana:
    service:
      nodePort: 30561
