apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-service.fullname" . }}-config
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
data:
  KEYCLOAK_INTERNAL_HOST: {{ .Values.global.keycloak.internalHost | quote }}
  KEYCLOAK_INTERNAL_PORT: {{ .Values.global.keycloak.internalPort | quote }}
  KEYCLOAK_ISSUER_HOST: {{ .Values.global.keycloak.issuerHost | quote }}
  KEYCLOAK_ISSUER_PORT: {{ .Values.global.keycloak.issuerPort | quote }}
