apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elk.logstash.fullname" . }}-config
  labels:
    {{- include "elk.logstash.labels" . | nindent 4 }}
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json_lines
      }
    }

    filter {
      mutate {
        rename => { "service" => "service_name" }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://{{ include "elk.elasticsearch.fullname" . }}:{{ .Values.elasticsearch.service.port }}"]
        index => "bank-logs-%{+YYYY.MM.dd}"
      }
    }
