apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "elk.elasticsearch.fullname" . }}-init
  labels:
    {{- include "elk.elasticsearch.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "elk.elasticsearch.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: curlimages/curl:8.5.0
          command: ["/bin/sh", "/init/init.sh"]
          volumeMounts:
            - name: init-script
              mountPath: /init
      volumes:
        - name: init-script
          configMap:
            name: {{ include "elk.elasticsearch.fullname" . }}-init-script
            defaultMode: 0755
