apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.scrapeInterval }}
    scrape_configs:
      - job_name: bank-backend
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
{{- range .Values.scrapeTargets.backend }}
            - {{ . }}
{{- end }}
      - job_name: bank-front
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
{{- range .Values.scrapeTargets.front }}
            - {{ . }}
{{- end }}
